name: Build & deploy React frontend to Azure Web App

on:
  push:
    branches: [ master ]      # same branch you used before
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # required by actions/checkout

    steps:
      # 1) Get the code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2) Node.js toolchain
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # 3) Install & build
      - name: Install dependencies
        run: npm ci            # faster & reproducible
      - name: Build React app
        run: npm run build     # produces ./build

      # 4) (Optional) run tests
      # - name: Run tests
      #   run: npm test --if-present

      # 5) Deploy the *build* folder only
      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: novalearn-lms-with-mern-stack   # your App Service
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEA5474795C64C84B539838D9BFC1A2F }}
          package: ./build                           # <-- critical change
